//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordLadder.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordLadder.Infrastructure.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Answer File name was not informed.
        /// </summary>
        public static string AnswerFileNameNotInformed {
            get {
                return ResourceManager.GetString("AnswerFileNameNotInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Word is not on Words Dictionary: Start Word = {0}.
        /// </summary>
        public static string EndWordIsNotOnList {
            get {
                return ResourceManager.GetString("EndWordIsNotOnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Word has not the same Length as Words Length provided: End Word = {0}({1}), Length: {2}).
        /// </summary>
        public static string EndWordNotSameLength {
            get {
                return ResourceManager.GetString("EndWordNotSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dictionary File does not exists in the path provided: {0}).
        /// </summary>
        public static string FileDoesNotExists {
            get {
                return ResourceManager.GetString("FileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was not enough words to transform from Start Word to the End Word to conclude the Word Ladder. Start Word: {0}, End Word: {1}.
        /// </summary>
        public static string NotEnoughWordsToTransform {
            get {
                return ResourceManager.GetString("NotEnoughWordsToTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no words returned from Result File.
        /// </summary>
        public static string NoWordsOnDictionary {
            get {
                return ResourceManager.GetString("NoWordsOnDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Word and End Word are not with the same Length: Start Word = {0}({1}), End Word = {2}({3}).
        /// </summary>
        public static string StartAndEndWordNotSameLength {
            get {
                return ResourceManager.GetString("StartAndEndWordNotSameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Word is not on Words Dictionary: Start Word = {0}.
        /// </summary>
        public static string StartWordIsNotOnList {
            get {
                return ResourceManager.GetString("StartWordIsNotOnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Word has not the same Length as Words Length provided: Start Word = {0}({1}), Length: {2}).
        /// </summary>
        public static string StartWordNotSameLength {
            get {
                return ResourceManager.GetString("StartWordNotSameLength", resourceCulture);
            }
        }
    }
}
